### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by r00bal** [r00bal/Gatsby-portfolio-starter#1]
- [ ] add a contact form
- [x] netlify integration 
- [ ] add portrait animation 
- [ ] add main svg animation 
- [ ] configure styled components
- [ ] clean the code
